version: '2'

services: 
  documents:
    container_name: documents
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '1234:1234'
      - '1235:1235'
    environment:
      - NODE_ENV=development